#!/bin/bash

mkdir $2

while [[ $# -gt 0 ]]; do 
  case $1 in
    -a)
      cp -a ~/texops/abstract/ $2/ 
      echo "an abstract! great."
      shift
      shift
      ;;
    -P)
      cp -a ~/texops/paper/ $2/ 
      echo "wow! a paper!"
      shift
      shift
      ;;
    -p)
      cp -a ~/texops/poster/ $2/ 
      echo "hey! a poster!"
      shift
      shift
      ;;
    -s)
      cp -a ~/texops/slides/ $2/ 
      echo "yay! slides!"
      shift
      shift
      ;;
    -t)
      cp -a ~/texops/templates.tex $2/ 
      echo "added a templates file. use it wisely."
      shift
      shift
      ;;
  esac
done
